// implementations/vue/src/components/ShowDetailsDialog.vue
<template>
    <v-dialog v-model="open" fullscreen hide-overlay transition="dialog-bottom-transition" v-if="info">
        <v-card>
            <v-toolbar dark color="primary">
                <v-btn icon dark @click="close">
                    <v-icon>close</v-icon>
                </v-btn>
                <v-toolbar-title>{{info.name}}</v-toolbar-title>
                <v-spacer></v-spacer>
            </v-toolbar>
            <v-container grid-list-xl fluid>
                <v-layout row wrap>
                    <v-flex xs12><a :href="info.website" target="_blank">Go to website</a></v-flex>
                    <v-flex xs6>
                        <img class="image" :src="info.image.original" :alt="info.name">
                    </v-flex>
                    <v-flex xs6>
                        <div v-html="info.summary"></div>
                    </v-flex>
                    <v-flex xs12 v-if="hasCast" tag="h2">Cast</v-flex>
                    <v-flex v-if="hasCast && actor.character.image && actor.character.image.medium"
                            v-for="actor in cast" :key="actor.person.id" shrink>
                        <v-card>
                            <div>
                                {{actor.person.name}}
                                <hr/>
                                {{actor.character.name}}
                            </div>
                            <img class="img-actor" :src="actor.character.image.medium">
                        </v-card>
                    </v-flex>
                </v-layout>
            </v-container>
        </v-card>
    </v-dialog>
</template>

<script>
  import { mapActions } from 'redux-vuex';

  export default {
    props: ['open', 'info'],
    computed: {
      hasCast: function() {
        return this.info._embedded && this.info._embedded.cast;
      },
      cast: function() {
        return this.info._embedded && this.info._embedded.cast || {};
      },
    },
    methods: mapActions({
      close: function() {
        this.$emit('close');
      },
    }),
    data() {
      return {};
    },
  };
</script>

<style>
    .image {
        width: 100%;
        height: auto;
    }

    .img-actor {
        margin-bottom: -6px;
    }

</style>

// implementations/react/src/app/components/ShowDetailsDialog.js
import React from 'react';
import renderHTML from 'react-render-html';
import { withStyles } from '@material-ui/core/styles';
import { Dialog, Slide, AppBar, Toolbar, IconButton, Typography, Grid } from '@material-ui/core';
import CloseIcon from '@material-ui/icons/Close';

const styles = {
  appBar: {
    position: 'relative',
  },
  body: {
    padding: 20,
  },
  flex: {
    flex: 1,
  },
  image: {
    width: '100%',
    height: 'auto',
  },
};

const Transition = (props) => {
  return <Slide direction="up" {...props} />;
};

class ShowDetailsDialog extends React.Component {

  render() {
    const { classes, isOpen, handleDialogClose, showInfo } = this.props;
    const { name, image, officialSite: website, summary, _embedded } = showInfo || {};
    return (

      <Dialog
        fullScreen
        open={isOpen}
        onClose={handleDialogClose}
        TransitionComponent={Transition}
      >
        <AppBar className={classes.appBar}>
          <Toolbar>
            <IconButton color="inherit" onClick={handleDialogClose} aria-label="Close">
              <CloseIcon />
            </IconButton>
            <Typography variant="h6" color="inherit" className={classes.flex}>
              {name}
            </Typography>

          </Toolbar>
        </AppBar>
        <div className={classes.body}>
          <Grid container spacing={40}>
            <Grid item xs={12}>
              {website && <a href={website} target={'_blank'}>Go to website</a>}
            </Grid>
            <Grid item xs={6}>
              {image && <img className={classes.image} src={image.original} alt={name} />}
            </Grid>
            <Grid item xs={6}>
              {renderHTML(summary || '')}
            </Grid>
            <Grid item xs={12}>
              <Grid container spacing={16}>
                <Grid item xs={12}>
                  <Typography
                    variant="h6" color="inherit" className={classes.flex}
                  >Cast</Typography>
                </Grid>
                {_embedded && _embedded.cast.map(({ person: { name: personName }, character: { name: characterName, image } }) => {
                  return !!(image && image.medium) && <Grid item>
                    <div>
                      {personName}
                      <hr />
                      {characterName}
                    </div>
                    {image && image.medium && <img src={image.medium} alt={characterName} />}
                  </Grid>;
                })}
              </Grid>
            </Grid>
          </Grid>
        </div>
      </Dialog>

    );
  }
}

export default withStyles(styles)(ShowDetailsDialog);
